python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_48 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 64 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 4 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_192_96 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 192 \
  --pred_len 96 \
  --seg_len 96 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_288_144 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 288 \
  --pred_len 144 \
  --seg_len 144 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 3 \
  --num_blocks 4 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_384_192 \
  --model Koopa \
  --data ETTh2 \
  --features M \
  --seq_len 384 \
  --pred_len 192 \
  --seg_len 192 \
  --dynamic_dim 64 \
  --hidden_dim 64 \
  --hidden_layers 2 \
  --num_blocks 1 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0