python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_48_24 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 48 \
  --pred_len 24 \
  --seg_len 24 \
  --dynamic_dim 128 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 4 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_72_36 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 72 \
  --pred_len 36 \
  --seg_len 36 \
  --dynamic_dim 512 \
  --hidden_dim 512 \
  --hidden_layers 3 \
  --num_blocks 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_96_48 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --seg_len 48 \
  --dynamic_dim 256 \
  --hidden_dim 512 \
  --hidden_layers 2 \
  --num_blocks 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/illness/ \
  --data_path national_illness.csv \
  --model_id ili_120_60 \
  --model Koopa \
  --data custom \
  --features M \
  --seq_len 120 \
  --pred_len 60 \
  --seg_len 60 \
  --dynamic_dim 64 \
  --hidden_dim 256 \
  --hidden_layers 4 \
  --num_blocks 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --itr 1 \
  --gpu 0